### ISSUE TITLE
Notificatiefunctie per SMS of soortgelijk bij overschrijden thresholds

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/HSNetmeter#4]
Slechts een idee. Mogelijkheid van een functie met alarm erop die een SMS of soortgelijk kan versturen, zodat je telefoon automagisch begint te gillen als de netfrequentie bijvoorbeeld langer dan een halve minuut onder 49,9 Hz zakt (of over 50,1 heen vliegt) en/of als er op bijvoorbeeld twee of meer locaties in de afgelopen minuut simultaan een spanningsdip is geconstateerd.

**Comment by BaDu-HSN** [comment]
Er zijn een aantal mogelijkheden:
- SMS (betrekkelijk eenvoudig)
- Twitter (eenvoudig)
- Whatsapp (is complex)
- Mail (simpel)
- Een eigen app die echt begint te gillen (veel werk)

**Comment by BaDu-HSN** [comment]
Not for now
