### ISSUE TITLE
HW: ADC Opnemen

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/HSNetmeter#7]
Waarschijnlijk is een MCP300x goed in te passen.
In principe is 1 kanaal voldoende.

**Comment by BaDu-HSN** [comment]
MCP3008 lijkt overkill, maar is goedkoper dan een MCP3001/3002/3004.
Willen we de overige analoge waarden extern aan kunnen sluiten?

**Comment by Marcello83** [comment]
Ik zal even uitzoeken welke types er ondersteund worden.

**Comment by BaDu-HSN** [comment]
Wont fix in first revision
