### ISSUE TITLE
Elektor-project als voorbeeld

### ISSUE THREAD

**Issue by reening** [Hoogspanningsnet/HSNetmeter#8]
Het bestand was te groot als bijlage op het forum, en GitHub had weinig andere mogelijkheden om deze bestanden te uploaden. Dan maar als issue: [netfrequentie.pdf](https://github.com/Hoogspanningsnet/HSNetmeter/files/1813177/netfrequentie.pdf)

**Comment by BaDu-HSN** [comment]
Nais! Dit is een leuke schakeling en wellicht iets om met V2.0 toe te voegen.
Ik zou dan wel het low-pass filter op een andere frequentie leggen zodat we de harmonische vervormingen op de gestandaardiseerde methode (zie netcode) kunnen meten. 
Deze schrijft voor dat je t/m de 40e harmonische moet meten (geeft lowpass van 2kHz).
In theorie heb je geen low-pass nodig en kan je evt beperken op je RPI bij de fourier-transformatie
De trafo filtert hier waarschijnlijk ook al

**Comment by BaDu-HSN** [comment]
Wont fix in this revision
